Model\Payment\Group\BankAccount:

    type: embeddable

    fields:
        id:
            type: integer
            column: bank_account_id
            nullable: true
        lastPairing:
            type: datetime_immutable
            nullable: true
