Model\Payment\Group\Email:

    type: entity
    table: pa_group_email

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        type:
            type: string_enum
            annotations:
                enum: { class: Model\Payment\EmailType }
        enabled:
            type: boolean

    embedded:
        template:
            class: Model\Payment\EmailTemplate


    manyToOne:
        group:
            targetEntity: Model\Payment\Group
            inversedBy: emails
