version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nasext/dependent-select-box
    versions:
    - ">= 4.0.a, < 4.1"
  - dependency-name: nette/security
    versions:
    - ">= 3.0.a, < 3.1"
  - dependency-name: league/flysystem
    versions:
    - 2.0.4
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
  open-pull-requests-limit: 10
  reviewers:
  - fmasa
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.1.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
    - 1.3.8
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
