version: "3.4"

services:
    app:
        ports:
            - 80:80
        volumes:
            - /var/www/html/temp
    mysql:
        ports:
            - 3306:3306

    adminer:
        container_name: hskauting.adminer
        image: adminer
        ports:
            - 8080:8080
        networks:
            main:
                aliases:
                    - mysql
volumes:
    mysql:
        name: hskauting_mysql
        external: true
