version: '3.4'

services:
    app:
        container_name: hskauting.app
        image: fmasa/lebeda:7.4
        volumes:
            - www:/var/www
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            DEVELOPMENT_MACHINE: 'true'
        networks:
            main:
                aliases:
                    - moje-hospodareni.cz

    mysql:
        container_name: hskauting.mysql
        image: mysql:8.0
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: hskauting
        networks:
            main:
                aliases:
                    - mysql

    mysql-test:
        container_name: hskauting.mysql-test
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: hskauting
        networks:
            main:
                aliases:
                    - mysql-test

    chrome:
        container_name: hskauting.chrome
        image: selenium/standalone-chrome:3.141
        networks:
            main:
                aliases:
                    - chrome

    smtp:
        container_name: hskauting.smtp
        image: tophfr/mailcatcher:0.6.5_3
        environment:
            SMTP_HOST: smtp-hospodareni.loc
        networks:
            main:
                aliases:
                    - smtp-hospodareni.loc
        ports:
            - 1080:1080

volumes:
    mysql:
    www:

networks:
    main:
