version: "3"

services:
    app:
        ports:
            - 80:80
        volumes:
            - /var/www/html/nette-temp
    mysql:
        ports:
            - 3306:3306
volumes:
    mysql:
        name: hskauting_mysql
        external: true
