Model\Cashbook\Cashbook\Chit:

    type: entity
    table: ac_chits

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        number:
            type: chit_number
            nullable: true
            column: num
        date: { type: chronos_date }
        recipient:
            type: recipient
            nullable: true
        purpose:
            type: string
        locked:
            column: '`lock`'
            type: integer
            nullable: true

    embedded:
        amount:
            class: Model\Cashbook\Cashbook\Amount
            columnPrefix: false
        category:
            class: Model\Cashbook\Cashbook\Category
            columnPrefix: false

    manyToOne:
        cashbook:
            targetEntity: Model\Cashbook\Cashbook
            inversedBy: chits
            joinColumn:
                name: eventId
                referencedColumnName: id
