Model\Travel\Command\Travel:

    type: entity
    table: tc_travels

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        startPlace:
            type: string
        endPlace:
            type: string
        distance:
            type: float
        date:
            type: datetime_immutable
            column: start_date

    manyToOne:
        command:
            targetEntity: Model\Travel\Command
            inversedBy: travels
            joinColumn:
                name: command_id
                referencedColumnName: id

    embedded:
        transportType:
            class: Model\Travel\Command\TransportType
            columnPrefix: false
